INSERT INTO user VALUES(1000,'Tom');
INSERT INTO user VALUES(1001,'Jerry');
INSERT INTO user VALUES(1002,'Jack');

INSERT INTO role VALUES(1,'ROLE_ADMIN');
INSERT INTO role VALUES(2,'ROLE_USER');

INSERT INTO user_role VALUES(1000,1);
INSERT INTO user_role VALUES(1001,2);
INSERT INTO user_role VALUES(1002,1);
